#!/bin/bash 

USER=wozhub
AUTOSYN_GIT=/home/${USER}/git/auto-synergy

source $AUTOSYN_GIT/autosyn-env

isLoggedIn() {
  w -s -h | grep -q $1
}

getDisplay() {
  ps e -u $1 | sed -rn 's/.* DISPLAY=(:[0-9]*).*/\1/p' | sort -u | head -1
}

if [ "$2" != "up" ]; then
  exit 0  # nada que hacer
fi

# https://stackoverflow.com/questions/3173131/redirect-copy-of-stdout-to-log-file-from-within-bash-script-itself
# Redirect stdout ( > ) into a named pipe ( >() ) running "tee"
exec > >(tee -i ${AUTOSYN_DISPATCHER_LOG})
exec 2>&1

touch ${AUTOSYN_HELPER_LOG} &&
sudo chown ${USER} ${AUTOSYN_HELPER_LOG}

# Me aseguro de que haya iniciado sesion antes de correr el helper
while ! isLoggedIn ${USER}; do
	sleep 10
done && runuser -l ${USER} -c "DISPLAY=$(getDisplay ${USER}); ${AUTOSYN_GIT}/helper.sh &>/dev/null" &
