#!/bin/bash 

USER=wozhub
AUTOSYN_GIT=/home/$user/git/auto-synergy
LOG_FILE=/var/log/auto-synergy.log

isLoggedIn() {
  w -s -h | grep -q $1
}

if [ "$2" != "up" ]; then
  exit 0  # nada que hacer
fi

# https://stackoverflow.com/questions/3173131/redirect-copy-of-stdout-to-log-file-from-within-bash-script-itself
# Redirect stdout ( > ) into a named pipe ( >() ) running "tee"
exec > >(tee -i $log_file)
exec 2>&1

# Me aseguro de que haya iniciado sesion antes de correr el helper
while ! isLoggedIn ${USER}; do
	sleep 10
done && runuser -l ${USER} -c "DISPLAY=$(ps e -u ${USER} | sed -rn 's/.* DISPLAY=(:[0-9]*).*/\1/p' | sort -u | head -1); ${AUTOSYN_GIT}/helper.sh" &
