#!/bin/bash 

TOOLS_DIR=$(dirname $(realpath $BASH_SOURCE))
configs=$TOOLS_DIR/known_networks

autosyn-network-getCurrent() {  # Me fijo si tengo una configuracion para la red actual
  current=$(ip route show | grep `hostname -I | cut -f1 -d' '` | cut -f1 -d' ')
  
  for config in `ls $configs`; do
    if grep -q $current $configs/$config; then
      source $configs/$config
      return 0
    fi
  done

  return 1
}

autosyn-config-update() {
  # echo "${FUNCNAME[0]}: Actualizando configuración con ip [$1]"
  if autosyn-network-getCurrent; then
    # echo "${FUNCNAME[0]}: Archivo de configuración [$network_config]"
    if autosyn-host-test $1; then
    	    # echo "${FUNCNAME[0]}: IP con synergy activo [$server_ip]"
	    sed -i $network_config -e "s/$server_ip/$1/g"
	    return $?
    fi
  fi
  return 1
}

autosyn-mac2ip() {
    ip=$(autosyn-arp-getIp $2)
    if [ "$ip" != "" ]; then
        echo $ip
    else
	nmap -sP $1 &>/dev/null #escaneo la red para juntar mac address
        autosyn-arp-getIp $2
    fi
}

autosyn-arp-getIp() {
  #arp -a | grep $1 | grep -oP '\(\K[\d|\.]*'
  ip n | grep $1 | awk '{print $1}'
}

autosyn-host-test() { #me fijo si la ip esta encendida y escuchando
    
    if ! ping $1 -c 1 &>/dev/null; then
        return 1
    fi  # IP answers ICMP

    if ! nc -z $1 24800 &>/dev/null; then
        return 1
    fi  # Port is OPEN

    expect << EOF
log_user 0
spawn telnet $1 24800
expect -re "Synergy"
send "exit\r"
EOF
    return $?
}

autosyn-host-connect() {
    # https://askubuntu.com/questions/90234/wrong-keyboard-layout-on-client-pc-when-using-synergy
    . /etc/default/keyboard
    /usr/bin/synergyc --debug $debug_level --log /tmp/synergy $1
    DISPLAY=:0 setxkbmap $XKBLAYOUT \
        -option "$XKBOPTIONS" \
        -model "$XKBMODEL" \
        -variant "$XKBVARIANT"
}
