#!/bin/bash 

TOOLS_DIR=$(dirname $(realpath $BASH_SOURCE))
configs=$TOOLS_DIR/known_networks

findCurrentNetwork() {  # Me fijo si tengo una configuracion para la red actual
  current=$(ip route show | grep `hostname -I | cut -f1 -d' '` | cut -f1 -d' ')
  
  for config in `ls $configs`; do
    if grep -q $current $configs/$config; then
      source $configs/$config
      return 0
    fi
  done

  return 1
}

updateConfig() {
  # echo "${FUNCNAME[0]}: Actualizando configuración con ip [$1]"
  if findCurrentNetwork; then
    # echo "${FUNCNAME[0]}: Archivo de configuración [$network_config]"
    if testSynergy $1; then
    	    # echo "${FUNCNAME[0]}: IP con synergy activo [$server_ip]"
	    sed -i $network_config -e "s/$server_ip/$1/g"
	    return $?
    fi
  fi
  return 1
}

findIPfromMAC() {
    ip=$(arpFindIp $2)
    if [ "$ip" != "" ]; then
        echo $ip
    else
	nmap -sP $1 &>/dev/null #escaneo la red para juntar mac address
        arpFindIp $2
    fi
}

arpFindIp() {
  #arp -a | grep $1 | grep -oP '\(\K[\d|\.]*'
  ip n | grep $1 | awk '{print $1}'
}

testSynergy() { #me fijo si la ip esta encendida y escuchando
    
    if ! ping $1 -c 1 &>/dev/null; then
        return 1
    fi  # IP answers ICMP

    if ! nc -z $1 24800 &>/dev/null; then
        return 1
    fi  # Port is OPEN

    expect << EOF
log_user 0
spawn telnet $1 24800
expect -re "Synergy"
send "exit\r"
EOF
    return $?
}
